package com.gabriel.compilador.util;

import com.gabriel.compilador.model.Parse;
import com.gabriel.compilador.model.Simbolo;

public interface ConstantesUtil {

	String[] RESERVADAS = { 
		"AND", 
		"ARRAY", 
		"BEGIN", 
		"CALL", 
		"CASE", 
		"CONST", 
		"DO", 
		"ELSE", 
		"END", 
		"FOR", 
		"GOTO", 
		"IF",
		"INTEGER", 
		"LABEL", 
		"NOT", 
		"OF", 
		"OR", 
		"PROCEDURE", 
		"PROGRAM", 
		"READLN", 
		"REPEAT", 
		"THEN", 
		"TO", 
		"UNTIL",
		"VAR", 
		"WHILE", 
		"WRITELN" 
	};

	Simbolo[] SIMBOLOS_T = { 
		new Simbolo(1, "PROGRAM"), 
		new Simbolo(2, "LABEL"), 
		new Simbolo(3, "CONST"),
		new Simbolo(4, "VAR"), 
		new Simbolo(5, "PROCEDURE"), 
		new Simbolo(6, "BEGIN"), 
		new Simbolo(7, "END"),
		new Simbolo(8, "INTEGER"), 
		new Simbolo(9, "ARRAY"), 
		new Simbolo(10, "OF"), 
		new Simbolo(11, "CALL"),
		new Simbolo(12, "GOTO"), 
		new Simbolo(13, "IF"), 
		new Simbolo(14, "THEN"), 
		new Simbolo(15, "ELSE"),
		new Simbolo(16, "WHILE"), 
		new Simbolo(17, "DO"), 
		new Simbolo(18, "REPEAT"), 
		new Simbolo(19, "UNTIL"),
		new Simbolo(20, "READLN"), 
		new Simbolo(21, "WRITELN"), 
		new Simbolo(22, "OR"), 
		new Simbolo(23, "AND"),
		new Simbolo(24, "NOT"), 
		new Simbolo(25, "IDENTIFICADOR"), 
		new Simbolo(26, "INTEIRO"),
		new Simbolo(27, "FOR"), 
		new Simbolo(28, "TO"), 
		new Simbolo(29, "CASE"), 
		new Simbolo(30, "+"),
		new Simbolo(31, "-"), 
		new Simbolo(32, "*"), 
		new Simbolo(33, "/"), 
		new Simbolo(34, "["),
		new Simbolo(35, "]"), 
		new Simbolo(36, "("), 
		new Simbolo(37, ")"), 
		new Simbolo(38, ":="),
		new Simbolo(39, ":"), 
		new Simbolo(40, "="), 
		new Simbolo(41, ">"), 
		new Simbolo(42, ">="),
		new Simbolo(43, "<"), 
		new Simbolo(44, "<="), 
		new Simbolo(45, "<>"), 
		new Simbolo(46, ","),
		new Simbolo(47, ";"), 
		new Simbolo(48, "LITERAL"), 
		new Simbolo(49, "."), 
		new Simbolo(50, ".."),
		new Simbolo(51, "$") 
	};

	Simbolo[] SIMBOLOS_N = { 
		new Simbolo(52, "PROGRAMA"), 
		new Simbolo(53, "BLOCO"), 
		new Simbolo(54, "DCLROT"),
		new Simbolo(55, "LID"), 
		new Simbolo(56, "REPIDENT"), 
		new Simbolo(57, "DCLCONST"),
		new Simbolo(58, "LDCONST"), 
		new Simbolo(59, "DCLVAR"), 
		new Simbolo(60, "LDVAR"), 
		new Simbolo(61, "TIPO"),
		new Simbolo(62, "DCLPROC"), 
		new Simbolo(63, "DEFPAR"), 
		new Simbolo(64, "CORPO"),
		new Simbolo(65, "REPCOMANDO"), 
		new Simbolo(66, "COMANDO"), 
		new Simbolo(67, "RCOMID"),
		new Simbolo(68, "RVAR"), 
		new Simbolo(69, "PARAMETROS"), 
		new Simbolo(70, "REPPAR"),
		new Simbolo(71, "ELSEPARTE"), 
		new Simbolo(72, "VARIAVEL"), 
		new Simbolo(73, "VARIAVEL1"),
		new Simbolo(74, "REPVARIAVEL"), 
		new Simbolo(75, "ITEMSAIDA"), 
		new Simbolo(76, "REPITEM"),
		new Simbolo(77, "EXPRESSAO"), 
		new Simbolo(78, "REPEXPSIMP"), 
		new Simbolo(79, "EXPSIMP"),
		new Simbolo(80, "REPEXP"), 
		new Simbolo(81, "TERMO"), 
		new Simbolo(82, "REPTERMO"), 
		new Simbolo(83, "FATOR"),
		new Simbolo(84, "CONDCASE"), 
		new Simbolo(85, "CONTCASE"), 
		new Simbolo(86, "RPINTEIRO"),
		new Simbolo(87, "SEM EFEITO") 
	};
	
	Parse[] TABELA_PARSE = {
		new Parse(52, 1, "PROGRAM|IDENTIFICADOR|;|BLOCO|."),
		
		new Parse(53, 2, "DCLROT|DCLCONST|DCLVAR|DCLPROC|CORPO"),
		new Parse(53, 3, "DCLROT|DCLCONST|DCLVAR|DCLPROC|CORPO"),
		new Parse(53, 4, "DCLROT|DCLCONST|DCLVAR|DCLPROC|CORPO"),
		new Parse(53, 5, "DCLROT|DCLCONST|DCLVAR|DCLPROC|CORPO"),
		new Parse(53, 6, "DCLROT|DCLCONST|DCLVAR|DCLPROC|CORPO"),

		new Parse(54, 2, "LABEL|LID|;"),
		new Parse(54, 3, ""),
		new Parse(54, 4, ""),
		new Parse(54, 5, ""),
		new Parse(54, 6, ""),
		
		new Parse(55, 25, "IDENTIFICADOR|REPIDENT"),
		
		new Parse(56, 39, ""),
		new Parse(56, 46, ",|IDENTIFICADOR|REPIDENT"),		
		new Parse(56, 47, ""),
		
		new Parse(57, 3, "CONST|IDENTIFICADOR|=|INTEIRO|;|LDCONST"),
		new Parse(57, 4, ""),
		new Parse(57, 5, ""),
		new Parse(57, 6, ""),
		
		new Parse(58, 4, ""),
		new Parse(58, 5, ""),
		new Parse(58, 6, ""),
		new Parse(58, 25, "IDENTIFICADOR|=|INTEIRO|;|LDCONST"),
		
		new Parse(59, 4, "VAR|LID|:|TIPO|;|LDVAR"),
		new Parse(59, 5, ""),
		new Parse(59, 6, ""),
		
		new Parse(60, 5, ""),
		new Parse(60, 6, ""),
		new Parse(60, 25, "LID|:|TIPO|;|LDVAR"),
		
		new Parse(61, 8, "INTEGER"),
		new Parse(61, 9, "ARRAY|[|INTEIRO|..|INTEIRO|]|OF|INTEGER"),
		
		new Parse(62, 5, "PROCEDURE|IDENTIFICADOR|DEFPAR|;|BLOCO|;|DCLPROC"),
		new Parse(62, 6, ""),
		
		new Parse(63, 36, "(|LID|:|INTEGER|)"),
		new Parse(63, 39, ""),
		
		new Parse(64, 6, "BEGIN|COMANDO|REPCOMANDO|END"),
		
		new Parse(65, 7, ""),
		new Parse(65, 47, ";|COMANDO|REPCOMANDO"),
		
		new Parse(66, 6, "CORPO"),
		new Parse(66, 7, ""),
		new Parse(66, 11, "CALL|IDENTIFICADOR|PARAMETROS"),
		new Parse(66, 12, "GOTO|IDENTIFICADOR"),
		new Parse(66, 13, "IF|EXPRESSAO|THEN|COMANDO|ELSEPARTE"),
		new Parse(66, 15, ""),
		new Parse(66, 16, "WHILE|EXPRESSAO|DO|COMANDO"),
		new Parse(66, 18, "REPEAT|COMANDO|UNTIL|EXPRESSAO"),
		new Parse(66, 19, ""),
		new Parse(66, 20, "READLN|(|VARIAVEL|REPVARIAVEL|)"),
		new Parse(66, 21, "WRITELN|(|ITEMSAIDA|REPITEM|)"),		
		new Parse(66, 25, "IDENTIFICADOR|RCOMID"),
		new Parse(66, 27, "FOR|IDENTIFICADOR|:=|EXPRESSAO|TO|EXPRESSAO|DO|COMANDO"),
		new Parse(66, 29, "CASE|EXPRESSAO|OF|CONDCASE|END"),
		new Parse(66, 47, ""),
		
		new Parse(67, 34, "RVAR|:=|EXPRESSAO"),
		new Parse(67, 38, "RVAR|:=|EXPRESSAO"),		
		new Parse(67, 39, ":|COMANDO"),
		
		new Parse(68, 34, "[|EXPRESSAO|]"),
		new Parse(68, 38, ""),
		
		new Parse(69, 7, ""),
		new Parse(69, 15, ""),
		new Parse(69, 19, ""),
		new Parse(69, 36, "(|EXPRESSAO|REPPAR|)"),
		new Parse(69, 47, ""),
		
		new Parse(70, 37, ""),
		new Parse(70, 46, ",|EXPRESSAO|REPPAR"),
		
		new Parse(71, 7, ""),
		new Parse(71, 15, "ELSE|COMANDO"),
		new Parse(71, 19, ""),
		new Parse(71, 47, ""),
		
		new Parse(72, 25, "IDENTIFICADOR|VARIAVEL1"),
		
		new Parse(73, 7, ""),
		new Parse(73, 10, ""),
		new Parse(73, 14, ""),
		new Parse(73, 15, ""),
		new Parse(73, 17, ""),
		new Parse(73, 19, ""),
		new Parse(73, 22, ""),
		new Parse(73, 23, ""),
		new Parse(73, 28, ""),
		new Parse(73, 30, ""),
		new Parse(73, 31, ""),
		new Parse(73, 32, ""),
		new Parse(73, 33, ""),
		new Parse(73, 34, "[|EXPRESSAO|]"),
		new Parse(73, 35, ""),
		new Parse(73, 37, ""),
		new Parse(73, 40, ""),
		new Parse(73, 41, ""),
		new Parse(73, 42, ""),
		new Parse(73, 43, ""),
		new Parse(73, 44, ""),
		new Parse(73, 45, ""),
		new Parse(73, 46, ""),
		new Parse(73, 47, ""),
		
		new Parse(74, 37, ""),
		new Parse(74, 46, ",|VARIAVEL|REPVARIAVEL"),
		
		new Parse(75, 24, "EXPRESSAO"),
		new Parse(75, 25, "EXPRESSAO"),
		new Parse(75, 26, "EXPRESSAO"),
		new Parse(75, 30, "EXPRESSAO"),
		new Parse(75, 31, "EXPRESSAO"),
		new Parse(75, 36, "EXPRESSAO"),
		new Parse(75, 48, "LITERAL"),
		
		new Parse(76, 37, ""),
		new Parse(76, 46, ",|ITEMSAIDA|REPITEM"),
		
		new Parse(77, 24, "EXPSIMP|REPEXPSIMP"),
		new Parse(77, 25, "EXPSIMP|REPEXPSIMP"),
		new Parse(77, 26, "EXPSIMP|REPEXPSIMP"),
		new Parse(77, 30, "EXPSIMP|REPEXPSIMP"),
		new Parse(77, 31, "EXPSIMP|REPEXPSIMP"),
		new Parse(77, 36, "EXPSIMP|REPEXPSIMP"),
		
		new Parse(78, 7, ""),
		new Parse(78, 10, ""),
		new Parse(78, 14, ""),
		new Parse(78, 15, ""),
		new Parse(78, 17, ""),
		new Parse(78, 19, ""),
		new Parse(78, 28, ""),
		new Parse(78, 35, ""),
		new Parse(78, 37, ""),
		new Parse(78, 40, "=|EXPSIMP"),
		new Parse(78, 41, ">|EXPSIMP"),
		new Parse(78, 42, ">=|EXPSIMP"),
		new Parse(78, 43, "<|EXPSIMP"),
		new Parse(78, 44, "<=|EXPSIMP"),
		new Parse(78, 45, "<>|EXPSIMP"),
		new Parse(78, 46, ""),
		new Parse(78, 47, ""),
		
		new Parse(79, 24, "TERMO|REPEXP"),
		new Parse(79, 25, "TERMO|REPEXP"),
		new Parse(79, 26, "TERMO|REPEXP"),
		new Parse(79, 30, "+|TERMO|REPEXP"),
		new Parse(79, 31, "-|TERMO|REPEXP"),
		new Parse(79, 36, "TERMO|REPEXP"),
		
		new Parse(80, 7, ""),
		new Parse(80, 10, ""),
		new Parse(80, 14, ""),
		new Parse(80, 15, ""),
		new Parse(80, 17, ""),
		new Parse(80, 19, ""),
		new Parse(80, 22, "OR|TERMO|REPEXP"),
		new Parse(80, 28, ""),
		new Parse(80, 30, "+|TERMO|REPEXP"),
		new Parse(80, 31, "-|TERMO|REPEXP"),
		new Parse(80, 35, ""),
		new Parse(80, 37, ""),
		new Parse(80, 40, ""),
		new Parse(80, 41, ""),
		new Parse(80, 42, ""),
		new Parse(80, 43, ""),
		new Parse(80, 44, ""),
		new Parse(80, 45, ""),
		new Parse(80, 46, ""),
		new Parse(80, 47, ""),
		
		new Parse(81, 24, "FATOR|REPTERMO"),
		new Parse(81, 25, "FATOR|REPTERMO"),
		new Parse(81, 26, "FATOR|REPTERMO"),
		new Parse(81, 36, "FATOR|REPTERMO"),
		
		new Parse(82, 7, ""),
		new Parse(82, 10, ""),
		new Parse(82, 14, ""),
		new Parse(82, 15, ""),
		new Parse(82, 17, ""),
		new Parse(82, 19, ""),
		new Parse(82, 22, ""),
		new Parse(82, 23, "AND|FATOR|REPTERMO"),
		new Parse(82, 28, ""),
		new Parse(82, 30, ""),
		new Parse(82, 31, ""),
		new Parse(82, 32, "*|FATOR|REPTERMO"),
		new Parse(82, 33, "/|FATOR|REPTERMO"),
		new Parse(82, 35, ""),
		new Parse(82, 37, ""),
		new Parse(82, 40, ""),
		new Parse(82, 41, ""),
		new Parse(82, 42, ""),
		new Parse(82, 43, ""),
		new Parse(82, 44, ""),
		new Parse(82, 45, ""),
		new Parse(82, 46, ""),
		new Parse(82, 47, ""),
		
		new Parse(83, 24, "NOT|FATOR"),
		new Parse(83, 25, "VARIAVEL"),
		new Parse(83, 26, "INTEIRO"),
		new Parse(83, 36, "(|EXPRESSAO|)"),
		
		new Parse(84, 26, "INTEIRO|RPINTEIRO|:|COMANDO|CONTCASE"),
		
		new Parse(85, 7, ""),
		new Parse(85, 47, ";|CONDCASE"),
		
		new Parse(86, 39, ""),
		new Parse(86, 46, ",|INTEIRO|RPINTEIRO")
	};

}
